# Generated by Django 5.2.1 on 2025-05-24 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_address_first_name_remove_address_last_name_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_visited', models.DateTimeField(auto_now_add=True, verbose_name='Visited At')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='store.customer', verbose_name='customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_visits', to='store.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'User History',
                'verbose_name_plural': 'User Histories',
                'ordering': ['-datetime_visited'],
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
