# Generated by Django 5.2.1 on 2025-05-19 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendors',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProductVendor',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
