# Generated by Django 5.2.1 on 2025-05-21 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_vendors_remove_vendor_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOfQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('image', models.ImageField(upload_to='questions/', verbose_name='image')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='slug')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='datetime_created')),
            ],
            options={
                'verbose_name': 'CategoryOfQuestion',
                'verbose_name_plural': 'CategoryOfQuestions',
                'ordering': ['datetime_created'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('suggestion', 'Suggestion'), ('complaint', 'Complaint or Feedback'), ('order_tracking', 'Order Tracking'), ('after_sales', 'After-Sales Service'), ('warranty_inquiry', 'Warranty Inquiry'), ('management', 'Management'), ('accounting', 'Accounting and Financial Matters'), ('other', 'Other Topics')], max_length=50, verbose_name='Subject')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=11, verbose_name='Phone Number')),
                ('message', models.TextField(verbose_name='Message')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='contact_attachments/', verbose_name='Attachment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='question')),
                ('answer', models.TextField(verbose_name='answer')),
                ('long_answer', models.TextField(blank=True, null=True, verbose_name='long answer')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='slug')),
                ('repeat', models.BooleanField(default=False, verbose_name='repeat')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='datetime_created')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='store.categoryofquestion', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['-datetime_created'],
            },
        ),
    ]
