# Generated by Django 5.2.1 on 2025-05-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_categoryofquestion_contactmessage_questions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='QuestionsOfSites',
        ),
        migrations.AlterModelOptions(
            name='questionsofsites',
            options={'ordering': ['-datetime_created'], 'verbose_name': 'Question of site', 'verbose_name_plural': 'Questions of site'},
        ),
    ]
