# Generated by Django 5.2.1 on 2025-05-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_city_province_alter_address_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default=1, max_length=100, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(default=1, max_length=100, verbose_name='Province'),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-is_default', 'city'], 'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='mobile',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
