# Generated by Django 5.2.1 on 2025-05-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_address_city_alter_address_province_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='street',
        ),
        migrations.AddField(
            model_name='address',
            name='first_name',
            field=models.CharField(default=1, max_length=50, verbose_name='first_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='full_address',
            field=models.TextField(default=1, verbose_name='full_address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='last_name',
            field=models.CharField(default=1, max_length=50, verbose_name='last_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='mobile',
            field=models.CharField(default=1, max_length=11, verbose_name='mobile'),
            preserve_default=False,
        ),
    ]
