# Generated by Django 5.2.1 on 2025-05-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_address_street_address_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='last_name',
        ),
        migrations.AddField(
            model_name='address',
            name='recipient_last_name',
            field=models.CharField(default=1, max_length=50, verbose_name='recipient_last_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='recipient_name',
            field=models.CharField(default=1, max_length=50, verbose_name='recipient_name'),
            preserve_default=False,
        ),
    ]
