# Generated by Django 5.2.1 on 2025-11-28 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_address_first_name_remove_address_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-datetime_created'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
