# Generated by Django 5.2.1 on 2025-11-29 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255, unique=True, verbose_name='Search Term')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Search Count')),
                ('last_searched_at', models.DateTimeField(auto_now=True, verbose_name='Last Searched At')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to='store.category', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Search Query',
                'verbose_name_plural': 'Search Queries',
                'ordering': ['-count', '-last_searched_at'],
            },
        ),
    ]
