# Generated by Django 5.2.1 on 2025-11-30 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_searchquery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_search_default',
            field=models.BooleanField(default=False, help_text='If true, this category will be shown in the fixed search suggestions list.', verbose_name='Show in default search list'),
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, verbose_name='Search Query')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to='store.category', verbose_name='Category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Search Log',
                'verbose_name_plural': 'Search Logs',
                'ordering': ['-datetime_created'],
            },
        ),
        migrations.DeleteModel(
            name='SearchQuery',
        ),
    ]
